apiVersion: v1
kind: Pod
metadata:
  name: envfrom-demo
  labels:
    purpose: demonstrate-envfrom
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    envFrom:
    - configMapRef:
        name: envfrom-configmap